class Data(object):
    def __init__(self,VibrationX,VibrationY,MotorDisplacementX,MotorDisplacementY,PumpDisplacementX,
    PumpDisplacementY,MotorSpeed,ZeroSpeed,PumpOutletP1,PumpOutletP2,FilterPressure1,FilterPressure2,
    FirPreBeforeSeal,SecPreBeforeSeal,ThiPreBeforeSeal,UpperBearTemperature,UpperBearBushTemperature,
    LowerThrustBearBushTemperature,UpperThrustBearBushTemperature,UpMotorAirTemperature,StatorTemperatureU,
    StatorTemperatureV,StatorTemperatureW,LowMotorAirTemperature,LowerOilTemperature,LowerBearTemperature,
    CoolerInletTemperature,CoolerOutletTemperature,InjectWaterTemperature,ControlLeakageTemperature,
    ControlLeakageFlow,LowPressureLeakageFlow,InjectWaterFlow,CoolerSecFlow,UpperBearingOilLevel,
    LowerBearingOilLevel,SealPositionMonitor,FlywheelPositionMonitor):
        self.VibrationX=VibrationX
        self.VibrationY=VibrationY
        self.MotorDisplacementX=MotorDisplacementX
        self.MotorDisplacementY=MotorDisplacementY
        self.PumpDisplacementX=PumpDisplacementX
        self.PumpDisplacementY=PumpDisplacementY
        self.MotorSpeed=MotorSpeed
        self.ZeroSpeed=ZeroSpeed
        self.PumpOutletP1=PumpOutletP1
        self.PumpOutletP2=PumpOutletP2
        self.FilterPressure1=FilterPressure1
        self.FilterPressure2=FilterPressure2
        self.FirPreBeforeSeal=FirPreBeforeSeal
        self.SecPreBeforeSeal=SecPreBeforeSeal
        self.ThiPreBeforeSeal=ThiPreBeforeSeal
        self.UpperBearTemperature=UpperBearTemperature
        self.UpperBearBushTemperature=UpperBearBushTemperature
        self.LowerThrustBearBushTemperature=LowerThrustBearBushTemperature
        self.UpperThrustBearBushTemperature=UpperThrustBearBushTemperature
        self.UpMotorAirTemperature=UpMotorAirTemperature
        self.StatorTemperatureU=StatorTemperatureU
        self.StatorTemperatureV=StatorTemperatureV
        self.StatorTemperatureW=StatorTemperatureW
        self.LowMotorAirTemperature=LowMotorAirTemperature
        self.LowerOilTemperature=LowerOilTemperature
        self.LowerBearTemperature=LowerBearTemperature
        self.CoolerInletTemperature=CoolerInletTemperature
        self.CoolerOutletTemperature=CoolerOutletTemperature
        self.InjectWaterTemperature=InjectWaterTemperature
        self.ControlLeakageTemperature=ControlLeakageTemperature
        self.ControlLeakageFlow=ControlLeakageFlow
        self.LowPressureLeakageFlow=LowPressureLeakageFlow
        self.InjectWaterFlow=InjectWaterFlow
        self.CoolerSecFlow=CoolerSecFlow
        self.UpperBearingOilLevel=UpperBearingOilLevel
        self.LowerBearingOilLevel=LowerBearingOilLevel
        self.SealPositionMonitor=SealPositionMonitor
        self.FlywheelPositionMonitor=FlywheelPositionMonitor
